app:
  image: iojs:latest
  volumes:
    - /vagrant/crappy-contacts/:/var/www/ # evtl. :ro, wenn möglich
  working_dir: /var/www
  command: npm run-script watch
  ports:
    - "80:3000"
  expose:
    - "3000"
